{% set version = "0.3.3" %}

package:
  name: agate-lookup
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/agate-lookup/agate-lookup-{{ version }}.tar.gz
  sha256: 65ac2b627ffada4370537a1ad62e9c6b26fb07658fb029abcf927b9d0fbbba6d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - agate >=1.5.0
    - requests >=2.9.1
    - pyyaml >=3.11

test:
  imports:
    - agatelookup

about:
  home: http://agate-lookup.readthedocs.org/
  license: MIT
  license_file: COPYING
  license_family: MIT
  # license_file: COPYING - Non MANIFEST.in - see https://github.com/wireservice/agate-lookup/pull/22
  summary: 'agate-lookup adds remote lookup tables to agate.'
  doc_url: http://agate-lookup.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-lookup

extra:
  recipe-maintainers:
    - pmlandwehr
