{% set version = "0.3.2" %}

package:
  name: agate-lookup
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/agate-lookup/agate-lookup-{{ version }}.tar.gz
  sha256: e723549b4a3ca6c378b22a82e22e734c4424fd10a6e4f183b8cb7ef3ed5c904d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - agate >=1.5.0
    - requests >=2.9.1
    - pyyaml >=3.11

test:
  imports:
    - agatelookup

about:
  home: http://agate-lookup.readthedocs.org/
  license: MIT
  license_file: COPYING
  license_family: MIT
  # license_file: COPYING - Non MANIFEST.in - see https://github.com/wireservice/agate-lookup/pull/22
  summary: agate-lookup adds remote lookup tables to agate.
  doc_url: http://agate-lookup.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-lookup

extra:
  recipe-maintainers:
    - pmlandwehr
