travis:
  secure:
    BINSTAR_TOKEN: Yyzm1Oq+AA3m8eQd/0JIqEpnNMITOA+jdF+lpvHxoeAp3M29NUEkmcGMtk/sAzUNUHH1JDt81GbW7QnymH+9EAN2G+w6MLozl3k6BoEf1sebCER1KWtwthkTrYDctgvOx76yq2WCrRpOtkKyMyxEKtSCxXnqoPEQQwcfplPca4Hfma8X1ba53W2CHFnOI5VvnmREIBhwUjwpO87oK0kB+w4E2K/cY0TO+TB3aaGuuHyJfVPBppiIMRXMjs0qaorCRGN2ScvXePmvqTtisCipcqpnUY9A3dJpfJ7CQMK5Hs+nNPiW1Z40ymI2IuXYQz/+DDkpEJODO34nsI/CDD/P9+uh+vz0hTdivUengoLTgw5Yp8tafI/ai2sf196Yb5kB6IhruK+bkEaxUXg31FoFKpHBA2yGWfaFan9OybB9CaZ508UPxSMcIWmVU58nA0zMdCnLKXLlVhPbcCuN8k+GeEPTmkzM6iRpcpvxLKxtUFeHFiUxHPBI2ACaLweIE4EK3xM5nrTlOhfVM6Ab+89IYXTv1WbPFyUhJQ6B/e9f3doYOqk4rjwvxzYYZy93L1lMnk9uLLUBGDL4KU5Q7GmxXs8Jt4/YHRW7pSezCbslAOn2neIczBAKRRbXsR4vbhGnaAF/tDN/oFIi8+lwJgCkQtaPaNf3ZhxIAZ3Z4HAuem0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
