travis:
  secure:
    BINSTAR_TOKEN: gGj0ApYtPe2TLqrg464vXYoMi6wUt7G0VXgI1nv5oi5e8c6HH6/68xwB+lIyvPt5gt6d4tb4KUDbRpimpORKcgS1X9vl2DHeh+I7XOeo4kJ6U8exg5MTaRJClhtwmY2KrDSODpp3yOmZUA8Zal0Q7aDvZdBqoxG8sWaXCpJgpJFiQFEvVMAAJFxUzAdaLmvlxXhaHE2BO4v8TNqV8Xj6jTbHSoMOWcWXWz4nWGq3nZouO2xBZUDwT0F88XUG2jarPXzLiNoyq8KRwwApk3aOEYPbwEl16NdIZlmyfOIbz28zyKDeGDkCU9I/DFCE7/QyPHKf8UEexLVBsUJCZfS1c7YF8Hg8FsGFI5q/LjI9gDWcUzPiucGYTSGvvFxV8Qye0GFJEADLd+X+HjtI0ukAkM6YoYhvt77CWPTLbqIaO+enBYPKjCA9bPmc+BX6T9N120Fhu4NzM0bsLsLneJ+k0iKHCiDI7dgey2O316i4CnV5GHCMkcuYwMwTio+eYV1SDITvOKPLgb8muxerKKzqNx5LRwQzOzQET5q6juLqEbLnnina+jwV4Jf4watrUbFt0fGNSsAQ0RV/PR8UMTSoK5MCJ3NNvth5WniW1/vQG77GdFYEeQyduA6DTxoZOuRZkVgUf6g8EvCfFUxx8MVGhgmHvwLzViBFdhaO0NuIiiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
